### ISSUE TITLE
updating and back-compatibility

### ISSUE THREAD

**Issue by edenhochbaum** [Scalar-List-Utils/List-Util#2]
I'm looking to update List::Util from version 1.21 to the latest 1.42 on perl 5.16.2 

It looks like back-compatibility's preserved across 1.21-1.42, but I haven't seen any documentation guarantees to this effect.

Is there anything I should be looking out for here?

Also, there are cases where I've been using List::MoreUtils with exports of the unqualified names.  Are there cases where subroutine names collide between these 2 modules, where the functionality is different?

Thanks!

-Eden

**Comment by leonerd** [comment]
Hi,

First off - this isn't the real branch... this is a random test project I've not got around to releasing yet. Secondly, Scalar-List-Utils distribution issues should go on RT; see
  https://rt.cpan.org/Dist/Display.html?Status=Active&Queue=Scalar-List-Utils

In any case, as a perl module (and a core module especially) I try very hard to maintain forward compatibility; that is, an inplace upgrade to a later version really should be fine.

As for functions whose name is the same as other functions in other modules of the same name, you'd have to inspect the documentation in each case to compare them. Specifically in the case of things inspired by LMU, I sometimes make them the same, sometimes they're a little different for whatever reason. When switching from some function to some other function provided by a different module, you'll always want to be testing the things you care about in any case; here's no different from anything else.

**Comment by edenhochbaum** [comment]
Hi Paul, thanks very much for your helpful response, and sorry I didn't realize I was looking at a test branch!
